// Package oui resolves a MAC address to the organisation that owns its
// address block, using the IEEE registries as the authoritative source.
//
// Three registries matter, not one. IEEE hands out blocks at three sizes —
// MA-L (24 bits), MA-M (28 bits) and MA-S (36 bits) — and a MAC from a small
// block shares its first 24 bits with the registrar that resold it. Matching
// only 24 bits would therefore attribute a device to the wrong company, so
// lookups go longest-prefix first: 36, then 28, then 24.
//
// The full registries are an opt-in download (Settings/Datasets), exactly like
// the GeoLite2 and network-category datasets. Without them a small built-in
// table still covers common lab and home hardware, so the feature degrades
// instead of disappearing.
package oui

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
)

const (
	storeFile    = "oui.json"
	storeVersion = 1
)

// Info records what is installed, for Settings/Datasets.
type Info struct {
	Present     bool   `json:"present"`
	FetchedAt   string `json:"fetchedAt,omitempty"`
	PrefixCount int    `json:"prefixCount"`
	Registries  string `json:"registries,omitempty"` // e.g. "MA-L, MA-M, MA-S"
	Source      string `json:"source"`
}

type store struct {
	Version    int               `json:"version"`
	FetchedAt  string            `json:"fetchedAt"`
	Registries string            `json:"registries"`
	Prefixes   map[string]string `json:"prefixes"` // uppercase hex prefix -> organisation
}

// Engine holds the loaded registry. Safe for concurrent use.
type Engine struct {
	mu       sync.RWMutex
	dataDir  string
	prefixes map[string]string
	info     Info
}

// New returns an Engine reading from dataDir. A missing store is not an error.
func New(dataDir string) *Engine {
	e := &Engine{dataDir: dataDir}
	_ = e.Reload()
	return e
}

// Reload re-reads the store from disk.
func (e *Engine) Reload() error {
	raw, err := os.ReadFile(filepath.Join(e.dataDir, storeFile))
	if err != nil {
		e.mu.Lock()
		e.prefixes, e.info = nil, Info{Source: sourceLabel}
		e.mu.Unlock()
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	var s store
	if err := json.Unmarshal(raw, &s); err != nil {
		return fmt.Errorf("%s ilegible: %w", storeFile, err)
	}
	if s.Version != storeVersion {
		return fmt.Errorf("%s tiene versión %d, se esperaba %d — volvé a descargarlo", storeFile, s.Version, storeVersion)
	}
	e.mu.Lock()
	e.prefixes = s.Prefixes
	e.info = Info{
		Present: len(s.Prefixes) > 0, FetchedAt: s.FetchedAt,
		PrefixCount: len(s.Prefixes), Registries: s.Registries, Source: sourceLabel,
	}
	e.mu.Unlock()
	return nil
}

// Info reports what is installed.
func (e *Engine) Info() Info {
	e.mu.RLock()
	defer e.mu.RUnlock()
	return e.info
}

// Lookup returns the organisation that owns mac's address block, or "" when
// nothing matches. It accepts any common MAC formatting.
func (e *Engine) Lookup(mac string) string {
	norm := normalize(mac)
	if len(norm) < 6 {
		return ""
	}

	e.mu.RLock()
	prefixes := e.prefixes
	e.mu.RUnlock()

	// Longest prefix first: an MA-S assignment (36 bits) must win over the
	// MA-L block (24 bits) it lives inside, or the device is credited to the
	// registrar rather than to whoever actually built it.
	for _, n := range []int{9, 7, 6} {
		if len(norm) < n {
			continue
		}
		if v, ok := prefixes[norm[:n]]; ok {
			return v
		}
	}
	// Built-in fallback covers common hardware when the registries aren't
	// installed; it is 24-bit only, so it is checked last.
	if v, ok := builtin[norm[:6]]; ok {
		return v
	}
	// A locally administered address is never in any IEEE registry — it was
	// generated by the device, not assigned. Saying "unknown manufacturer"
	// there is misleading: the absence is the answer, and it usually means
	// phone MAC randomisation, a virtual machine or a container.
	if LocallyAdministered(mac) {
		return "dirección local (aleatoria)"
	}
	return ""
}

// Detail is the full breakdown of one MAC, for the lookup tool. It explains
// not just who owns the block but *why* the answer is what it is: which
// prefix matched, from which IEEE registry, and whether the address is one
// that could never have a manufacturer in the first place.
type Detail struct {
	Input     string `json:"input"`
	MAC       string `json:"mac,omitempty"` // normalizada a aa:bb:cc:dd:ee:ff
	Valid     bool   `json:"valid"`
	Vendor    string `json:"vendor,omitempty"`
	Prefix    string `json:"prefix,omitempty"`   // el prefijo que coincidió
	Registry  string `json:"registry,omitempty"` // MA-L | MA-M | MA-S | tabla integrada
	Local     bool   `json:"local"`              // administrada localmente (aleatoria)
	Multicast bool   `json:"multicast"`
	Broadcast bool   `json:"broadcast"`
	Note      string `json:"note,omitempty"`
}

// registryFor names the IEEE registry a prefix length belongs to.
func registryFor(digits int) string {
	switch digits {
	case 6:
		return "MA-L (24 bits)"
	case 7:
		return "MA-M (28 bits)"
	case 9:
		return "MA-S (36 bits)"
	}
	return ""
}

// LookupDetail resolves a MAC and explains the result.
func (e *Engine) LookupDetail(mac string) Detail {
	d := Detail{Input: strings.TrimSpace(mac)}
	norm := normalize(mac)
	if len(norm) < 12 {
		if len(norm) >= 6 {
			d.Note = "solo se reconoció un prefijo; una MAC completa tiene 12 dígitos hexadecimales"
		} else {
			d.Note = "no parece una dirección MAC"
			return d
		}
	} else {
		norm = norm[:12]
		d.Valid = true
	}

	// Formato legible, siempre en minúsculas y con dos puntos.
	var parts []string
	for i := 0; i+2 <= len(norm); i += 2 {
		parts = append(parts, strings.ToLower(norm[i:i+2]))
	}
	d.MAC = strings.Join(parts, ":")

	d.Local = LocallyAdministered(norm)
	if first, err := strconv.ParseUint(norm[:2], 16, 8); err == nil {
		d.Multicast = first&0x01 != 0
	}
	d.Broadcast = strings.EqualFold(norm, "FFFFFFFFFFFF")

	e.mu.RLock()
	prefixes := e.prefixes
	e.mu.RUnlock()

	for _, n := range []int{9, 7, 6} {
		if len(norm) < n {
			continue
		}
		if v, ok := prefixes[norm[:n]]; ok {
			d.Vendor, d.Prefix, d.Registry = v, norm[:n], registryFor(n)
			return d
		}
	}
	if v, ok := builtin[norm[:6]]; ok {
		d.Vendor, d.Prefix, d.Registry = v, norm[:6], "tabla integrada"
		return d
	}

	switch {
	case d.Broadcast:
		d.Note = "dirección de difusión: se entrega a todos los equipos del segmento, no identifica a ningún fabricante"
	case d.Local:
		d.Note = "administrada localmente: la generó el propio equipo, no la asignó el IEEE. Es lo normal en aleatorización de MAC de móviles, máquinas virtuales y contenedores"
	case d.Multicast:
		d.Note = "dirección multicast: identifica un grupo, no un equipo"
	default:
		d.Note = "sin coincidencia en los registros instalados. Puede ser un bloque asignado después de la última descarga, o una MAC inventada"
	}
	return d
}

// LocallyAdministered reports whether a MAC was self-assigned rather than
// allocated by IEEE, which is the second-least-significant bit of the first
// octet (RFC 7042 §2.1).
func LocallyAdministered(mac string) bool {
	norm := normalize(mac)
	if len(norm) < 2 {
		return false
	}
	first, err := strconv.ParseUint(norm[:2], 16, 8)
	if err != nil {
		return false
	}
	return first&0x02 != 0
}

// normalize strips separators and uppercases, so "b8:27:eb:…", "B8-27-EB-…"
// and "b827eb…" all resolve the same way.
func normalize(mac string) string {
	var b strings.Builder
	for _, r := range mac {
		switch {
		case r >= '0' && r <= '9', r >= 'A' && r <= 'F':
			b.WriteRune(r)
		case r >= 'a' && r <= 'f':
			b.WriteRune(r - 32)
		}
	}
	return b.String()
}
