// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePcap(arg1) {
  return window['go']['api']['Service']['AnalyzePcap'](arg1);
}

export function AnalyzeVoIP(arg1) {
  return window['go']['api']['Service']['AnalyzeVoIP'](arg1);
}

export function BGPASNObservatory(arg1) {
  return window['go']['api']['Service']['BGPASNObservatory'](arg1);
}

export function BGPBogonLookup(arg1) {
  return window['go']['api']['Service']['BGPBogonLookup'](arg1);
}

export function BGPCountryObservatory(arg1) {
  return window['go']['api']['Service']['BGPCountryObservatory'](arg1);
}

export function BGPGlobalObservatory() {
  return window['go']['api']['Service']['BGPGlobalObservatory']();
}

export function BGPHistory(arg1) {
  return window['go']['api']['Service']['BGPHistory'](arg1);
}

export function BGPNeighbours(arg1) {
  return window['go']['api']['Service']['BGPNeighbours'](arg1);
}

export function BGPOverview(arg1) {
  return window['go']['api']['Service']['BGPOverview'](arg1);
}

export function BGPPrefixes(arg1) {
  return window['go']['api']['Service']['BGPPrefixes'](arg1);
}

export function BGPRPKIObservatory(arg1) {
  return window['go']['api']['Service']['BGPRPKIObservatory'](arg1);
}

export function BGPRPKIValidate(arg1, arg2) {
  return window['go']['api']['Service']['BGPRPKIValidate'](arg1, arg2);
}

export function BGPRealtimeInfo(arg1) {
  return window['go']['api']['Service']['BGPRealtimeInfo'](arg1);
}

export function BGPRoutingStatus(arg1) {
  return window['go']['api']['Service']['BGPRoutingStatus'](arg1);
}

export function BGPSecurity(arg1) {
  return window['go']['api']['Service']['BGPSecurity'](arg1);
}

export function BGPTopology(arg1) {
  return window['go']['api']['Service']['BGPTopology'](arg1);
}

export function BGPlay(arg1) {
  return window['go']['api']['Service']['BGPlay'](arg1);
}

export function CancelSession(arg1) {
  return window['go']['api']['Service']['CancelSession'](arg1);
}

export function CancelUpdateDownload() {
  return window['go']['api']['Service']['CancelUpdateDownload']();
}

export function Capabilities() {
  return window['go']['api']['Service']['Capabilities']();
}

export function CaptureAvailable() {
  return window['go']['api']['Service']['CaptureAvailable']();
}

export function CaptureDevices() {
  return window['go']['api']['Service']['CaptureDevices']();
}

export function CheckForUpdates(arg1) {
  return window['go']['api']['Service']['CheckForUpdates'](arg1);
}

export function CheckGeoUpdates(arg1) {
  return window['go']['api']['Service']['CheckGeoUpdates'](arg1);
}

export function ClassifyIP(arg1) {
  return window['go']['api']['Service']['ClassifyIP'](arg1);
}

export function Close() {
  return window['go']['api']['Service']['Close']();
}

export function ConnMonSnapshot() {
  return window['go']['api']['Service']['ConnMonSnapshot']();
}

export function DNSCompare(arg1, arg2, arg3) {
  return window['go']['api']['Service']['DNSCompare'](arg1, arg2, arg3);
}

export function DNSDiscoverSRVSIP(arg1, arg2, arg3) {
  return window['go']['api']['Service']['DNSDiscoverSRVSIP'](arg1, arg2, arg3);
}

export function DNSQuery(arg1, arg2, arg3, arg4) {
  return window['go']['api']['Service']['DNSQuery'](arg1, arg2, arg3, arg4);
}

export function DNSRecordTypes() {
  return window['go']['api']['Service']['DNSRecordTypes']();
}

export function DNSResolveSRVTargets(arg1, arg2) {
  return window['go']['api']['Service']['DNSResolveSRVTargets'](arg1, arg2);
}

export function DNSResolvers() {
  return window['go']['api']['Service']['DNSResolvers']();
}

export function DNSReversePTR(arg1, arg2, arg3) {
  return window['go']['api']['Service']['DNSReversePTR'](arg1, arg2, arg3);
}

export function DownloadUpdate() {
  return window['go']['api']['Service']['DownloadUpdate']();
}

export function EnrichNetDiag(arg1) {
  return window['go']['api']['Service']['EnrichNetDiag'](arg1);
}

export function ExposureCompare(arg1, arg2) {
  return window['go']['api']['Service']['ExposureCompare'](arg1, arg2);
}

export function GeoLookup(arg1) {
  return window['go']['api']['Service']['GeoLookup'](arg1);
}

export function GeoStatus() {
  return window['go']['api']['Service']['GeoStatus']();
}

export function GeoUpdateStatus() {
  return window['go']['api']['Service']['GeoUpdateStatus']();
}

export function HTTPInspect(arg1, arg2, arg3) {
  return window['go']['api']['Service']['HTTPInspect'](arg1, arg2, arg3);
}

export function IPCalcAggregate(arg1) {
  return window['go']['api']['Service']['IPCalcAggregate'](arg1);
}

export function IPCalcAnalyze(arg1) {
  return window['go']['api']['Service']['IPCalcAnalyze'](arg1);
}

export function IPCalcContains(arg1, arg2) {
  return window['go']['api']['Service']['IPCalcContains'](arg1, arg2);
}

export function IPCalcCustomerPlan(arg1, arg2) {
  return window['go']['api']['Service']['IPCalcCustomerPlan'](arg1, arg2);
}

export function IPCalcSplit(arg1, arg2) {
  return window['go']['api']['Service']['IPCalcSplit'](arg1, arg2);
}

export function IPCalcVLSM(arg1, arg2) {
  return window['go']['api']['Service']['IPCalcVLSM'](arg1, arg2);
}

export function InvestigationAddDiagnose(arg1, arg2) {
  return window['go']['api']['Service']['InvestigationAddDiagnose'](arg1, arg2);
}

export function InvestigationAddMonitorEvent(arg1, arg2) {
  return window['go']['api']['Service']['InvestigationAddMonitorEvent'](arg1, arg2);
}

export function InvestigationAddPcap(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['Service']['InvestigationAddPcap'](arg1, arg2, arg3, arg4, arg5);
}

export function InvestigationAddVoIPCall(arg1, arg2) {
  return window['go']['api']['Service']['InvestigationAddVoIPCall'](arg1, arg2);
}

export function InvestigationCreate(arg1, arg2) {
  return window['go']['api']['Service']['InvestigationCreate'](arg1, arg2);
}

export function InvestigationDelete(arg1) {
  return window['go']['api']['Service']['InvestigationDelete'](arg1);
}

export function InvestigationGet(arg1) {
  return window['go']['api']['Service']['InvestigationGet'](arg1);
}

export function InvestigationList() {
  return window['go']['api']['Service']['InvestigationList']();
}

export function InvestigationRemoveEntry(arg1, arg2) {
  return window['go']['api']['Service']['InvestigationRemoveEntry'](arg1, arg2);
}

export function InvestigationReport(arg1) {
  return window['go']['api']['Service']['InvestigationReport'](arg1);
}

export function InvestigationUpdateEntryNote(arg1, arg2, arg3) {
  return window['go']['api']['Service']['InvestigationUpdateEntryNote'](arg1, arg2, arg3);
}

export function InvestigationUpdateMetadata(arg1, arg2, arg3) {
  return window['go']['api']['Service']['InvestigationUpdateMetadata'](arg1, arg2, arg3);
}

export function LabReport(arg1) {
  return window['go']['api']['Service']['LabReport'](arg1);
}

export function LabRunScenario(arg1) {
  return window['go']['api']['Service']['LabRunScenario'](arg1);
}

export function LabScenarios() {
  return window['go']['api']['Service']['LabScenarios']();
}

export function LanDiscover() {
  return window['go']['api']['Service']['LanDiscover']();
}

export function LanTrustAssess(arg1) {
  return window['go']['api']['Service']['LanTrustAssess'](arg1);
}

export function ListSessions() {
  return window['go']['api']['Service']['ListSessions']();
}

export function MACLookup(arg1) {
  return window['go']['api']['Service']['MACLookup'](arg1);
}

export function MACVendor(arg1) {
  return window['go']['api']['Service']['MACVendor'](arg1);
}

export function MonitorAddTarget(arg1) {
  return window['go']['api']['Service']['MonitorAddTarget'](arg1);
}

export function MonitorClearBaseline(arg1) {
  return window['go']['api']['Service']['MonitorClearBaseline'](arg1);
}

export function MonitorCompareToBaseline(arg1) {
  return window['go']['api']['Service']['MonitorCompareToBaseline'](arg1);
}

export function MonitorCompareWindows(arg1, arg2) {
  return window['go']['api']['Service']['MonitorCompareWindows'](arg1, arg2);
}

export function MonitorHistory(arg1, arg2) {
  return window['go']['api']['Service']['MonitorHistory'](arg1, arg2);
}

export function MonitorListTargets() {
  return window['go']['api']['Service']['MonitorListTargets']();
}

export function MonitorPinBaseline(arg1, arg2, arg3) {
  return window['go']['api']['Service']['MonitorPinBaseline'](arg1, arg2, arg3);
}

export function MonitorRemoveTarget(arg1) {
  return window['go']['api']['Service']['MonitorRemoveTarget'](arg1);
}

export function MonitorReport(arg1, arg2, arg3) {
  return window['go']['api']['Service']['MonitorReport'](arg1, arg2, arg3);
}

export function NetClassRemove(arg1) {
  return window['go']['api']['Service']['NetClassRemove'](arg1);
}

export function NetClassSources() {
  return window['go']['api']['Service']['NetClassSources']();
}

export function NetClassUpdate(arg1) {
  return window['go']['api']['Service']['NetClassUpdate'](arg1);
}

export function OUIInfo() {
  return window['go']['api']['Service']['OUIInfo']();
}

export function OUIRemove() {
  return window['go']['api']['Service']['OUIRemove']();
}

export function OUIUpdate() {
  return window['go']['api']['Service']['OUIUpdate']();
}

export function PassiveOSINT(arg1, arg2) {
  return window['go']['api']['Service']['PassiveOSINT'](arg1, arg2);
}

export function PhoneAnalyze(arg1, arg2) {
  return window['go']['api']['Service']['PhoneAnalyze'](arg1, arg2);
}

export function PublicIP() {
  return window['go']['api']['Service']['PublicIP']();
}

export function QuickDiagnose(arg1) {
  return window['go']['api']['Service']['QuickDiagnose'](arg1);
}

export function RDAPLookupASN(arg1) {
  return window['go']['api']['Service']['RDAPLookupASN'](arg1);
}

export function RDAPLookupDomain(arg1) {
  return window['go']['api']['Service']['RDAPLookupDomain'](arg1);
}

export function RDAPLookupIP(arg1) {
  return window['go']['api']['Service']['RDAPLookupIP'](arg1);
}

export function ReputationAssess(arg1) {
  return window['go']['api']['Service']['ReputationAssess'](arg1);
}

export function SaveGeoUpdateSettings(arg1, arg2, arg3) {
  return window['go']['api']['Service']['SaveGeoUpdateSettings'](arg1, arg2, arg3);
}

export function SelfTestLocal() {
  return window['go']['api']['Service']['SelfTestLocal']();
}

export function SetUpdateAutoCheck(arg1) {
  return window['go']['api']['Service']['SetUpdateAutoCheck'](arg1);
}

export function StartSession(arg1) {
  return window['go']['api']['Service']['StartSession'](arg1);
}

export function TLSInspect(arg1, arg2, arg3) {
  return window['go']['api']['Service']['TLSInspect'](arg1, arg2, arg3);
}

export function ThreatFeedRemove(arg1) {
  return window['go']['api']['Service']['ThreatFeedRemove'](arg1);
}

export function ThreatFeedSources() {
  return window['go']['api']['Service']['ThreatFeedSources']();
}

export function ThreatFeedUpdate(arg1) {
  return window['go']['api']['Service']['ThreatFeedUpdate'](arg1);
}

export function UpdateAutoCheckEnabled() {
  return window['go']['api']['Service']['UpdateAutoCheckEnabled']();
}

export function UpdateStatus() {
  return window['go']['api']['Service']['UpdateStatus']();
}

export function VoipQualityAddTarget(arg1) {
  return window['go']['api']['Service']['VoipQualityAddTarget'](arg1);
}

export function VoipQualityCompareWindows(arg1, arg2) {
  return window['go']['api']['Service']['VoipQualityCompareWindows'](arg1, arg2);
}

export function VoipQualityHistory(arg1, arg2) {
  return window['go']['api']['Service']['VoipQualityHistory'](arg1, arg2);
}

export function VoipQualityListTargets() {
  return window['go']['api']['Service']['VoipQualityListTargets']();
}

export function VoipQualityRemoveTarget(arg1) {
  return window['go']['api']['Service']['VoipQualityRemoveTarget'](arg1);
}

export function WebIntelAnalyze(arg1, arg2) {
  return window['go']['api']['Service']['WebIntelAnalyze'](arg1, arg2);
}

export function WifiAvailable() {
  return window['go']['api']['Service']['WifiAvailable']();
}

export function WifiPosture(arg1) {
  return window['go']['api']['Service']['WifiPosture'](arg1);
}

export function WifiScan() {
  return window['go']['api']['Service']['WifiScan']();
}

export function WifiStatus() {
  return window['go']['api']['Service']['WifiStatus']();
}
