// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {voip} from '../models';
import {bgp} from '../models';
import {capture} from '../models';
import {update} from '../models';
import {geoupdate} from '../models';
import {dnsintel} from '../models';
import {netdiag} from '../models';
import {serviceaudit} from '../models';
import {geoip} from '../models';
import {httpintel} from '../models';
import {ipcalc} from '../models';
import {monitor} from '../models';
import {correlation} from '../models';
import {investigation} from '../models';
import {report} from '../models';
import {lab} from '../models';
import {lan} from '../models';
import {oui} from '../models';
import {netclass} from '../models';
import {phoneintel} from '../models';
import {rdap} from '../models';
import {reputation} from '../models';
import {tlsintel} from '../models';
import {threatfeed} from '../models';
import {quality} from '../models';
import {webintel} from '../models';
import {wifi} from '../models';

export function AnalyzePcap(arg1:string):Promise<api.PcapResult>;

export function AnalyzeVoIP(arg1:string):Promise<voip.Result>;

export function BGPASNObservatory(arg1:bgp.ASNObservatoryRequest):Promise<bgp.ASNObservatoryResult>;

export function BGPBogonLookup(arg1:bgp.BogonLookupRequest):Promise<bgp.BogonLookupResult>;

export function BGPCountryObservatory(arg1:bgp.CountryObservatoryRequest):Promise<bgp.CountryObservatoryResult>;

export function BGPGlobalObservatory():Promise<bgp.GlobalRISObservatoryResult>;

export function BGPHistory(arg1:bgp.BGPHistoryRequest):Promise<bgp.BGPHistoryResult>;

export function BGPNeighbours(arg1:number):Promise<bgp.ASNNeighboursResult>;

export function BGPOverview(arg1:string):Promise<bgp.Overview>;

export function BGPPrefixes(arg1:bgp.PrefixPageRequest):Promise<bgp.PrefixPage>;

export function BGPRPKIObservatory(arg1:bgp.RPKIObservatoryRequest):Promise<bgp.RPKIObservatoryResult>;

export function BGPRPKIValidate(arg1:number,arg2:string):Promise<bgp.RPKIStatus>;

export function BGPRealtimeInfo(arg1:string):Promise<bgp.RealtimeSessionInfo>;

export function BGPRoutingStatus(arg1:string):Promise<bgp.RouteStatus>;

export function BGPSecurity(arg1:string):Promise<bgp.SecurityResult>;

export function BGPTopology(arg1:string):Promise<bgp.Graph>;

export function BGPlay(arg1:bgp.BGPlayRequest):Promise<bgp.BGPlayResult>;

export function CancelSession(arg1:string):Promise<void>;

export function CancelUpdateDownload():Promise<void>;

export function Capabilities():Promise<api.Capabilities>;

export function CaptureAvailable():Promise<boolean>;

export function CaptureDevices():Promise<Array<capture.Device>>;

export function CheckForUpdates(arg1:boolean):Promise<update.ReleaseInfo>;

export function CheckGeoUpdates(arg1:boolean):Promise<geoupdate.Result>;

export function ClassifyIP(arg1:string):Promise<api.AddrReport>;

export function Close():Promise<void>;

export function ConnMonSnapshot():Promise<api.ConnMonSnapshot>;

export function DNSCompare(arg1:string,arg2:string,arg3:boolean):Promise<dnsintel.Comparison>;

export function DNSDiscoverSRVSIP(arg1:string,arg2:string,arg3:boolean):Promise<Array<dnsintel.SRVDiscoveryCandidate>>;

export function DNSQuery(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<dnsintel.QueryResult>;

export function DNSRecordTypes():Promise<Array<string>>;

export function DNSResolveSRVTargets(arg1:Array<string>,arg2:string):Promise<Array<dnsintel.TargetResolution>>;

export function DNSResolvers():Promise<Array<dnsintel.Resolver>>;

export function DNSReversePTR(arg1:string,arg2:string,arg3:boolean):Promise<dnsintel.QueryResult>;

export function DownloadUpdate():Promise<void>;

export function EnrichNetDiag(arg1:netdiag.Result):Promise<netdiag.Result>;

export function ExposureCompare(arg1:Array<number>,arg2:Array<number>):Promise<serviceaudit.ExposureResult>;

export function GeoLookup(arg1:string):Promise<geoip.Result>;

export function GeoStatus():Promise<Array<geoip.DatasetInfo>>;

export function GeoUpdateStatus():Promise<geoupdate.Status>;

export function HTTPInspect(arg1:string,arg2:string,arg3:number):Promise<httpintel.Result>;

export function IPCalcAggregate(arg1:Array<string>):Promise<Array<string>>;

export function IPCalcAnalyze(arg1:string):Promise<ipcalc.Info>;

export function IPCalcContains(arg1:string,arg2:string):Promise<boolean>;

export function IPCalcCustomerPlan(arg1:number,arg2:boolean):Promise<ipcalc.CustomerPlan>;

export function IPCalcSplit(arg1:string,arg2:number):Promise<ipcalc.SplitResult>;

export function IPCalcVLSM(arg1:string,arg2:Array<ipcalc.VLSMRequest>):Promise<ipcalc.VLSMResult>;

export function InvestigationAddDiagnose(arg1:string,arg2:string):Promise<api.InvestigationAddResult>;

export function InvestigationAddMonitorEvent(arg1:string,arg2:monitor.DegradationEvent):Promise<api.InvestigationAddResult>;

export function InvestigationAddPcap(arg1:string,arg2:correlation.PcapIncidentSummary,arg3:string,arg4:string,arg5:string):Promise<api.InvestigationAddResult>;

export function InvestigationAddVoIPCall(arg1:string,arg2:voip.Call):Promise<api.InvestigationAddResult>;

export function InvestigationCreate(arg1:string,arg2:string):Promise<investigation.Investigation>;

export function InvestigationDelete(arg1:string):Promise<void>;

export function InvestigationGet(arg1:string):Promise<investigation.Investigation>;

export function InvestigationList():Promise<investigation.ListResult>;

export function InvestigationRemoveEntry(arg1:string,arg2:string):Promise<void>;

export function InvestigationReport(arg1:string):Promise<report.Report>;

export function InvestigationUpdateEntryNote(arg1:string,arg2:string,arg3:string):Promise<investigation.Entry>;

export function InvestigationUpdateMetadata(arg1:string,arg2:string,arg3:string):Promise<investigation.Investigation>;

export function LabReport(arg1:string):Promise<report.Report>;

export function LabRunScenario(arg1:string):Promise<lab.RunResult>;

export function LabScenarios():Promise<Array<lab.Scenario>>;

export function LanDiscover():Promise<lan.Report>;

export function LanTrustAssess(arg1:Array<lan.HostResult>):Promise<lan.TrustResult>;

export function ListSessions():Promise<Array<api.SessionInfo>>;

export function MACLookup(arg1:string):Promise<oui.Detail>;

export function MACVendor(arg1:string):Promise<string>;

export function MonitorAddTarget(arg1:monitor.Target):Promise<monitor.Target>;

export function MonitorClearBaseline(arg1:string):Promise<void>;

export function MonitorCompareToBaseline(arg1:string):Promise<monitor.BaselineComparison>;

export function MonitorCompareWindows(arg1:string,arg2:number):Promise<monitor.WindowComparison>;

export function MonitorHistory(arg1:string,arg2:number):Promise<monitor.History>;

export function MonitorListTargets():Promise<Array<api.MonitorTargetInfo>>;

export function MonitorPinBaseline(arg1:string,arg2:number,arg3:number):Promise<monitor.BaselineProfile>;

export function MonitorRemoveTarget(arg1:string):Promise<void>;

export function MonitorReport(arg1:string,arg2:number,arg3:number):Promise<report.Report>;

export function NetClassRemove(arg1:string):Promise<void>;

export function NetClassSources():Promise<Array<netclass.SourceInfo>>;

export function NetClassUpdate(arg1:string):Promise<netclass.SourceInfo>;

export function OUIInfo():Promise<oui.Info>;

export function OUIRemove():Promise<void>;

export function OUIUpdate():Promise<oui.Info>;

export function PassiveOSINT(arg1:string,arg2:boolean):Promise<api.PassiveOSINTResult>;

export function PhoneAnalyze(arg1:string,arg2:string):Promise<phoneintel.Result>;

export function PublicIP():Promise<api.PublicIPResult>;

export function QuickDiagnose(arg1:string):Promise<api.DiagnoseResult>;

export function RDAPLookupASN(arg1:number):Promise<rdap.Result>;

export function RDAPLookupDomain(arg1:string):Promise<rdap.DomainResult>;

export function RDAPLookupIP(arg1:string):Promise<rdap.Result>;

export function ReputationAssess(arg1:string):Promise<reputation.Score>;

export function SaveGeoUpdateSettings(arg1:string,arg2:string,arg3:boolean):Promise<geoupdate.Status>;

export function SelfTestLocal():Promise<api.SelfTestResult>;

export function SetUpdateAutoCheck(arg1:boolean):Promise<void>;

export function StartSession(arg1:string):Promise<api.SessionInfo>;

export function TLSInspect(arg1:string,arg2:number,arg3:string):Promise<tlsintel.Result>;

export function ThreatFeedRemove(arg1:string):Promise<void>;

export function ThreatFeedSources():Promise<Array<threatfeed.SourceInfo>>;

export function ThreatFeedUpdate(arg1:string):Promise<threatfeed.SourceInfo>;

export function UpdateAutoCheckEnabled():Promise<boolean>;

export function UpdateStatus():Promise<update.StatusSnapshot>;

export function VoipQualityAddTarget(arg1:quality.Target):Promise<quality.Target>;

export function VoipQualityCompareWindows(arg1:string,arg2:number):Promise<quality.WindowComparison>;

export function VoipQualityHistory(arg1:string,arg2:number):Promise<quality.History>;

export function VoipQualityListTargets():Promise<Array<quality.Target>>;

export function VoipQualityRemoveTarget(arg1:string):Promise<void>;

export function WebIntelAnalyze(arg1:string,arg2:string):Promise<webintel.Result>;

export function WifiAvailable():Promise<boolean>;

export function WifiPosture(arg1:Array<wifi.Network>):Promise<wifi.PostureResult>;

export function WifiScan():Promise<Array<wifi.Network>>;

export function WifiStatus():Promise<Array<wifi.IfaceStatus>>;
