// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bgp} from '../models';
import {report} from '../models';
import {voip} from '../models';
import {api} from '../models';
import {serviceaudit} from '../models';
import {throughput} from '../models';

export function BGPRealtimeStart(arg1:string):Promise<bgp.RealtimeSessionInfo>;

export function BGPRealtimeStop(arg1:string):Promise<void>;

export function ExportCallAudio(arg1:string,arg2:number,arg3:string):Promise<string>;

export function ExportSessionReport(arg1:report.Report,arg2:string):Promise<string>;

export function ExportVoIPCallAudio(arg1:string,arg2:voip.Call,arg3:string):Promise<string>;

export function InstallUpdate():Promise<void>;

export function InvestigationExportReport(arg1:string,arg2:string):Promise<string>;

export function LabExportReport(arg1:string,arg2:string):Promise<string>;

export function MonitorExportReport(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function MonitorStart(arg1:string):Promise<void>;

export function MonitorStop(arg1:string):Promise<void>;

export function PickPcapFile():Promise<string>;

export function PreviewVoIPCallAudio(arg1:string,arg2:voip.Call,arg3:string):Promise<string>;

export function Service():Promise<api.Service>;

export function ServiceAudit(arg1:string,arg2:number,arg3:boolean):Promise<serviceaudit.Result>;

export function SetWindowBackground(arg1:string):Promise<void>;

export function StartCapture(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<string>;

export function StartConnMon(arg1:number,arg2:boolean):Promise<string>;

export function StartDiagnose(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function StartHTTPLoad(arg1:string,arg2:string,arg3:number,arg4:number,arg5:Record<string, string>,arg6:string,arg7:number,arg8:boolean):Promise<string>;

export function StartLanScan(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function StartMTR(arg1:string,arg2:number,arg3:number,arg4:number,arg5:boolean,arg6:boolean):Promise<string>;

export function StartPing(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:boolean):Promise<string>;

export function StartScan(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<string>;

export function StartScanAdvanced(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:boolean):Promise<string>;

export function StartTZSPCapture(arg1:string,arg2:boolean):Promise<string>;

export function StartThroughput(arg1:string,arg2:throughput.Params):Promise<string>;

export function StartThroughputServer(arg1:string):Promise<string>;

export function StartTrace(arg1:string,arg2:number,arg3:number,arg4:number,arg5:boolean,arg6:boolean):Promise<string>;

export function StartVoIPAnalysis(arg1:string):Promise<string>;

export function StopCapture(arg1:string):Promise<void>;

export function StopConnMon(arg1:string):Promise<void>;

export function StopDiagnose(arg1:string):Promise<void>;

export function StopHTTPLoad(arg1:string):Promise<void>;

export function StopLanScan(arg1:string):Promise<void>;

export function StopMTR(arg1:string):Promise<void>;

export function StopPing(arg1:string):Promise<void>;

export function StopScan(arg1:string):Promise<void>;

export function StopThroughput(arg1:string):Promise<void>;

export function StopThroughputServer():Promise<void>;

export function StopTrace(arg1:string):Promise<void>;

export function StopVoIPAnalysis(arg1:string):Promise<void>;

export function SystemThemePreference():Promise<string>;

export function ThroughputAccessCode():Promise<string>;

export function ThroughputServerAddr():Promise<string>;
