// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BGPRealtimeStart(arg1) {
  return window['go']['main']['App']['BGPRealtimeStart'](arg1);
}

export function BGPRealtimeStop(arg1) {
  return window['go']['main']['App']['BGPRealtimeStop'](arg1);
}

export function ExportCallAudio(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportCallAudio'](arg1, arg2, arg3);
}

export function ExportSessionReport(arg1, arg2) {
  return window['go']['main']['App']['ExportSessionReport'](arg1, arg2);
}

export function ExportVoIPCallAudio(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportVoIPCallAudio'](arg1, arg2, arg3);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function InvestigationExportReport(arg1, arg2) {
  return window['go']['main']['App']['InvestigationExportReport'](arg1, arg2);
}

export function LabExportReport(arg1, arg2) {
  return window['go']['main']['App']['LabExportReport'](arg1, arg2);
}

export function MonitorExportReport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MonitorExportReport'](arg1, arg2, arg3, arg4);
}

export function MonitorStart(arg1) {
  return window['go']['main']['App']['MonitorStart'](arg1);
}

export function MonitorStop(arg1) {
  return window['go']['main']['App']['MonitorStop'](arg1);
}

export function PickPcapFile() {
  return window['go']['main']['App']['PickPcapFile']();
}

export function PreviewVoIPCallAudio(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewVoIPCallAudio'](arg1, arg2, arg3);
}

export function Service() {
  return window['go']['main']['App']['Service']();
}

export function ServiceAudit(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServiceAudit'](arg1, arg2, arg3);
}

export function SetWindowBackground(arg1) {
  return window['go']['main']['App']['SetWindowBackground'](arg1);
}

export function StartCapture(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartCapture'](arg1, arg2, arg3, arg4);
}

export function StartConnMon(arg1, arg2) {
  return window['go']['main']['App']['StartConnMon'](arg1, arg2);
}

export function StartDiagnose(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDiagnose'](arg1, arg2, arg3);
}

export function StartHTTPLoad(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['StartHTTPLoad'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function StartLanScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartLanScan'](arg1, arg2, arg3);
}

export function StartMTR(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartMTR'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartPing(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartPing'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartScan(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3, arg4, arg5);
}

export function StartScanAdvanced(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['StartScanAdvanced'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function StartTZSPCapture(arg1, arg2) {
  return window['go']['main']['App']['StartTZSPCapture'](arg1, arg2);
}

export function StartThroughput(arg1, arg2) {
  return window['go']['main']['App']['StartThroughput'](arg1, arg2);
}

export function StartThroughputServer(arg1) {
  return window['go']['main']['App']['StartThroughputServer'](arg1);
}

export function StartTrace(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartTrace'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartVoIPAnalysis(arg1) {
  return window['go']['main']['App']['StartVoIPAnalysis'](arg1);
}

export function StopCapture(arg1) {
  return window['go']['main']['App']['StopCapture'](arg1);
}

export function StopConnMon(arg1) {
  return window['go']['main']['App']['StopConnMon'](arg1);
}

export function StopDiagnose(arg1) {
  return window['go']['main']['App']['StopDiagnose'](arg1);
}

export function StopHTTPLoad(arg1) {
  return window['go']['main']['App']['StopHTTPLoad'](arg1);
}

export function StopLanScan(arg1) {
  return window['go']['main']['App']['StopLanScan'](arg1);
}

export function StopMTR(arg1) {
  return window['go']['main']['App']['StopMTR'](arg1);
}

export function StopPing(arg1) {
  return window['go']['main']['App']['StopPing'](arg1);
}

export function StopScan(arg1) {
  return window['go']['main']['App']['StopScan'](arg1);
}

export function StopThroughput(arg1) {
  return window['go']['main']['App']['StopThroughput'](arg1);
}

export function StopThroughputServer() {
  return window['go']['main']['App']['StopThroughputServer']();
}

export function StopTrace(arg1) {
  return window['go']['main']['App']['StopTrace'](arg1);
}

export function StopVoIPAnalysis(arg1) {
  return window['go']['main']['App']['StopVoIPAnalysis'](arg1);
}

export function SystemThemePreference() {
  return window['go']['main']['App']['SystemThemePreference']();
}

export function ThroughputAccessCode() {
  return window['go']['main']['App']['ThroughputAccessCode']();
}

export function ThroughputServerAddr() {
  return window['go']['main']['App']['ThroughputServerAddr']();
}
